
# Final NumPy Assignment
# Inputs khud se create karna hai



# Q1. Array Creation and Attributes

## Problem Statement
Create array [10,20,30,40,50] and print shape, ndim, size and dtype.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [3]:
# Write your code here
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(5,)
1
5
int64



# Q2. Matrix Creation

## Problem Statement
Create a 3x3 NumPy matrix and print it.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
# Write your code here


# Q3. Indexing Practice

## Problem Statement
Print first, third and last element from an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [4]:
# Write your code here
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[3])
print(arr[-1])
print(arr[-3])

40
50
30



# Q4. Slicing Practice

## Problem Statement
Print elements from index 2 to 5.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [23]:
# Write your code hereimport numpy as np
a=np.array([10,20,30,40,50,60,70])
print(arr[2:6])

[30 40 50 60]



# Q5. Fancy Indexing

## Problem Statement
Print selected elements using fancy indexing.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [15]:
# Write your code here
import numpy as np
arr = np.array([10,20,30,40,50,60])
arr[[0,2,4]]

array([10, 30, 50])


# Q6. Conditional Selection

## Problem Statement
Print values greater than 15.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [13]:
# Write your code here
arr=np.array([5,7,11,18,30])
np.where(arr>15)


(array([3, 4]),)


# Q7. Broadcasting

## Problem Statement
Add 10 to every element of an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [12]:
# Write your code here
import numpy as np
a=np.array([10,20,30,40])
print(a+10)

[20 30 40 50]



# Q8. Aggregate Functions

## Problem Statement
Print sum, mean, max and min.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [11]:
# Write your code here
arr=np.array([4,78,21,34,100,56])
#1. sum
print(f"sum is-{arr.sum()}")

#2. mean
print(f"mean is-{arr.mean()}")

#3. min
print(f"min is-{arr.min()}")

#4. max
print(f"max is-{arr.max()}")

sum is-293
mean is-48.833333333333336
min is-4
max is-100



# Q9. Sorting

## Problem Statement
Sort an unsorted NumPy array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [10]:
# Write your code here
array=np.array([2,10,56,1,54])
print(np.sort(array))


[ 1  2 10 54 56]



# Q10. Concatenation and Stacking

## Problem Statement
Perform concatenate and vstack on two arrays.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [9]:
# Write your code here
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate([a,b]))
print(np.vstack([a,b]))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
